### ISSUE TITLE
Dynamics definition in a vectorized way

### ISSUE THREAD

**Issue by lenassero** [anassinator/ilqr#4]
Hi, 

I have tried to implement cartpole's dynamics in a vectorized way (in cartpole.py) but it failed probably due to my lack of knowledge of Theano.

Basically, instead of defining them this way:

        f = T.stack([
            x + x_dot * dt,
            x_dot + x_dot_dot * dt,
            T.sin(next_theta),
            T.cos(next_theta),
            theta_dot + theta_dot_dot * dt,
        ])

define them somehow like this:

A = np.array([[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1]])
f = T.dot(A, [x, x_dot, sin_theta, cos_theta, theta_dot]) + T.stack([0, 0, T.sin(next_theta), T.cos(next_theta), 0]) + dt*T.stack([x_dot, x_dot_dot, 0, 0, theta_dot_dot])

I get the following error when running cartpole's notebook:

![image](https://user-images.githubusercontent.com/21358816/34578897-9c574860-f17e-11e7-9ad7-2f3bf9b84cb6.png)
![image](https://user-images.githubusercontent.com/21358816/34578904-ac863e9e-f17e-11e7-961f-112ce2fb78a6.png)

 Thank you for your help !

**Comment by anassinator** [comment]
Hi!

The way you defined it seems correct.
I believe I fixed it in #5, and it now works with your example. Could you give it a try and let me know?

Thanks

**Comment by anassinator** [comment]
@lenassero did the fix work for you?

**Comment by lenassero** [comment]
@anassinator I am sorry for the late reply, I have been very busy. Yes, it works now, thank you very much for the fix!

**Comment by anassinator** [comment]
Perfect thanks!
